//
// Created by TEUGUIA TADJUIDJE Rodolf Séderis on 4/12/2024 at 6:04:50 PM.
// Copyright (c) 2024 Rihen. All rights reserved.
//

#ifndef __NKENTSEU_KEYBOARD_H__
#define __NKENTSEU_KEYBOARD_H__

#pragma once

#include "System/System.h"
#include <System/Nature/Base.h>

namespace nkentseu {
    class NKENTSEU_API Keyboard {
    public:

        #define MASK (1<<30)
        #define SCANCODE_TO_KEYCODE(X)  (X | MASK)

        using Keycode = uint64;
        using Scancode = uint64;
        using KeyMod = uint64;
        using Code = uint64;

        enum : Code {
            NotDefine = 0,

            Escape,                // misc keys
            Tab,
            Backtab,
            Backspace,
            Return,
            Enter,
            Insert,
            Delete,
            Pause,
            Print,
            SysReq,
            Clear,
            Home,                // cursor movement
            End,
            Left,
            Up,
            Right,
            Down,
            PageUp,
            PageDown,
            ShiftLock,
            Shift,                // modifiers
            ShiftLeft,
            ShiftRight,
            Control,
            ControlLeft,
            ControlRight,
            Meta,
            MetaLeft,
            MetaRight,
            Alt,
            AltLeft,
            AltRight,
            CapsLock,
            NumLock,
            ScrollLock,

            F1,                // function keys
            F2,
            F3,
            F4,
            F5,
            F6,
            F7,
            F8,
            F9,
            F10,
            F11,
            F12,
            F13,
            F14,
            F15,
            F16,
            F17,
            F18,
            F19,
            F20,
            F21,
            F22,
            F23,
            F24,
            F25,
            F26,
            F27,
            F28,
            F29,
            F30,
            F31,
            F32,
            F33,
            F34,
            F35,

            SuperLeft,
            SuperRight,
            Undo,
            Redo,
            Menu,
            Find,
            HyperLeft,
            HyperRight,
            Help,
            DirectionLeft,
            DirectionRight,
            Space,
            Any = Space,
            Exclam,
            QuoteDbl,
            NumberSign,
            Dollar,
            Percent,
            Ampersand,
            Apostrophe,
            ParenLeft,
            ParenRight,
            Asterisk,
            Plus,
            Comma,
            Minus,
            Period,
            Decimal = Period,
            Slash,
            Divide = Slash,

            Numpad0,
            Numpad1,
            Numpad2,
            Numpad3,
            Numpad4,
            Numpad5,
            Numpad6,
            Numpad7,
            Numpad8,
            Numpad9,

            Keypad0,
            Keypad1,
            Keypad2,
            Keypad3,
            Keypad4,
            Keypad5,
            Keypad6,
            Keypad7,
            Keypad8,
            Keypad9,

            Colon,
            Semicolon,
            Less,
            Equal,
            Greater,
            Question,
            At,

            A,
            B,
            C,
            D,
            E,
            F,
            G,
            H,
            I,
            J,
            K,
            L,
            M,
            N,
            O,
            P,
            Q,
            R,
            S,
            T,
            U,
            V,
            W,
            X,
            Y,
            Z,
            
            Break,
            BracketLeft,
            Backslash,
            BracketRight,
            AsciiCircum,
            Underscore,
            QuoteLeft,
            BraceLeft,
            Bar,
            BraceRight,
            AsciiTilde,

            Nobreakspace,
            Exclamdown,
            Cent,
            Sterling,
            Currency,
            Yen,
            Brokenbar,
            Section,
            Diaeresis,
            Copyright,
            Ordfeminine,
            Guillemotleft,
            Notsign,
            Hyphen,
            Registered,
            Macron,
            Degree,
            Plusminus,
            Twosuperior,
            Threesuperior,
            Acute,
            Mu,
            Paragraph,
            Periodcentered,
            Cedilla,
            Onesuperior,
            Masculine,
            Guillemotright,
            Onequarter,
            Onehalf,
            Threequarters,
            Questiondown,
            Agrave,
            Aacute,
            Acircumflex,
            Atilde,
            Adiaeresis,
            Aring,
            AE,
            Ccedilla,
            Egrave,
            Eacute,
            Ecircumflex,
            Ediaeresis,
            Igrave,
            Iacute,
            Icircumflex,
            Idiaeresis,
            ETH,
            Eth,
            Ntilde,
            Ograve,
            Oacute,
            Ocircumflex,
            Otilde,
            Odiaeresis,
            Multiply,
            Ooblique,
            Ugrave,
            Uacute,
            Ucircumflex,
            Udiaeresis,
            Yacute,
            THORN,
            Ssharp,
            Division,
            Ydiaeresis,

            AltGr,
            MultiKey,
            Codeinput,
            SingleCandidate,
            MultipleCandidate,
            PreviousCandidate,

            ModeSwitch,
            ScriptSwitch,

            Kanji,
            Muhenkan,
            HenkanMode,
            Henkan,
            Romaji,
            Hiragana,
            Katakana,
            HiraganaKatakana,
            Zenkaku,
            Hankaku,
            ZenkakuHankaku,
            Touroku,
            Massyo,
            KanaLock,
            KanaShift,
            EisuShift,
            EisuToggle,
            KanjiBangou,
            ZenKoho,
            MaeKoho,

            Hangul,
            HangulStart,
            HangulEnd,
            HangulHanja,
            HangulJamo,
            HangulRomaja,
            HangulCodeinput,
            HangulJeonja,
            HangulBanja,
            HangulPreHanja,
            HangulPostHanja,
            HangulSingleCandidate,
            HangulMultipleCandidate,
            HangulPreviousCandidate,
            HangulSpecial,
            Hangulswitch,

            DeadGrave,
            DeadAcute,
            DeadCircumflex,
            DeadTilde,
            DeadMacron,
            DeadBreve,
            DeadAbovedot,
            DeadDiaeresis,
            DeadAbovering,
            DeadDoubleacute,
            DeadCaron,
            DeadCedilla,
            DeadOgonek,
            DeadIota,
            DeadVoicedSound,
            DeadSemivoicedSound,
            DeadBelowdot,
            DeadHook,
            DeadHorn,

            Back,
            Forward,
            Stop,
            Refresh,
            VolumeDown,
            VolumeMute,
            VolumeUp,
            BassBoost,
            BassUp,
            BassDown,
            TrebleUp,
            TrebleDown,
            MediaPlay,
            MediaStop,
            MediaPrevious,
            MediaNext,
            MediaRecord,
            MediaPause,
            MediaTogglePlayPause,
            HomePage,
            Favorites,
            Search,
            Standby,
            OpenUrl,

            LaunchMail,
            LaunchMedia,
            Launch0,
            Launch1,
            Launch2,
            Launch3,
            Launch4,
            Launch5,
            Launch6,
            Launch7,
            Launch8,
            Launch9,
            LaunchA,
            LaunchB,
            LaunchC,
            LaunchD,
            LaunchE,
            LaunchF,

            MonBrightnessUp,
            MonBrightnessDown,
            KeyboardLightOnOff,
            KeyboardBrightnessUp,
            KeyboardBrightnessDown,
            PowerOff,
            WakeUp,
            Eject,
            ScreenSaver,
            WWW,
            Memo,
            LightBulb,
            Shop,
            History,
            AddFavorite,
            HotLinks,
            BrightnessAdjust,
            Finance,
            Community,
            AudioRewind,
            BackForward,
            ApplicationLeft,
            ApplicationRight,
            Book,
            CD,
            Calculator,
            ToDoList,
            ClearGrab,
            Close,
            Copy,
            Cut,
            Display,
            DOS,
            Documents,
            Excel,
            Explorer,
            Game,
            Go,
            iTouch,
            LogOff,
            Market,
            Meeting,
            MenuKB,
            MenuPB,
            MySites,
            News,
            OfficeHome,
            Option,
            Paste,
            Phone,
            Calendar,
            Reply,
            Reload,
            RotateWindows,
            RotationPB,
            RotationKB,
            Save,
            Send,
            Spell,
            SplitScreen,
            Support,
            TaskPane,
            Terminal,
            Tools,
            Travel,
            Video,
            Word,
            Xfer,
            ZoomIn,
            ZoomOut,
            Away,
            Messenger,
            WebCam,
            MailForward,
            Pictures,
            Music,
            Battery,
            Bluetooth,
            WLAN,
            UWB,
            AudioForward,
            AudioRepeat,
            AudioRandomPlay,
            Subtitle,
            AudioCycleTrack,
            Time,
            Hibernate,
            View,
            TopMenu,
            PowerDown,
            Suspend,
            ContrastAdjust,

            LaunchG,
            LaunchH,

            TouchpadToggle,
            TouchpadOn,
            TouchpadOff,

            MicMute,

            Red,
            Green,
            Yellow,
            Blue,

            ChannelUp,
            ChannelDown,

            MediaLast,

            Select,
            Yes,
            No,

            Cancel,
            Printer,
            Execute,
            Sleep,
            Play,
            Zoom,
            Jisho,
            Oyayubi_Left,
            Oyayubi_Right,

            Context1,
            Context2,
            Context3,
            Context4,
            Call,
            Hangup,
            Flip,
            ToggleCallHangup,
            VoiceDial,
            LastNumberRedial,

            Kana, //
            One,
            Junja,
            Final,
            Hanja,
            Off,

            Convert,
            NonConvert,
            Accept,
            ModeChange,
            PrintScreen,
            Apps,
            Separator,
            Attn,
            CrSel,
            ExSel,
            EraseEOF,
            NoName,
            Pa1,
            Quotation,
            Backtick,

            Camera,
            CameraFocus,
 
            FirstCode = Escape,
            LastCode = CameraFocus,
        };

        static std::string GetKeycode(Keycode keycode);
        static Keycode GetKeycode(const std::string& str);

        static std::string GetScancode(Scancode scancode);
        static Scancode GetScancode(const std::string& str);

        static bool IsKeyCode(Keycode key);
        static bool IsScanCode(Scancode key);
        static bool IsKeyMode(KeyMod key);

    private:

        static Code GetCodeFromName(const char* code);
        static const char* GetCodeName(Code code);

        static std::string ToString(Code code);
        static Code FromString(const std::string& str);
    };
    
    #define KEYBOARD(code) Keyboard::code
} // namespace nkentseu

#endif    // __NKENTSEU_KEYBOARD_H__